name: nubo
description: "App meteorol√≥gica Flutter - AEMET"
publish_to: 'none'
version: 0.1.17

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.0
  intl: ^0.20.0
  google_fonts: ^6.2.0
  geolocator: ^13.0.0
  shared_preferences: ^2.3.0
  lucide_icons_flutter: ^1.3.0
  xml: ^6.5.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  sunrise_sunset_calc: ^3.0.0
  lottie: ^3.3.2
  path_provider: ^2.1.5
  dio: ^5.9.1
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/nubo_icon.png"
  adaptive_icon_background: "assets/icon/nubo_background.png"
  adaptive_icon_foreground: "assets/icon/nubo_icon.png"
